/**
 * Generates CSS classes for all color themes
 * Run with: npx tsx scripts/generate-theme-css.ts
 */

import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Import theme colors from the source
import { THEME_COLORS } from "../src/lib/themeColors";

// Variables that themes override (subset of all variables)
const THEME_SPECIFIC_VARS = [
  "primary",
  "primary-foreground",
  "sidebar-primary",
  "chart-1",
  "chart-2",
  "chart-3",
  "chart-4",
  "chart-5",
];

// Base light/dark values (from neutral theme) for comparison
const BASE_LIGHT = {
  "primary-foreground": "oklch(0.985 0 0)",
};

const BASE_DARK = {
  "primary-foreground": "oklch(0.205 0 0)",
};

function generateThemeCSS(): string {
  const lines: string[] = [
    "/* Auto-generated theme classes - DO NOT EDIT MANUALLY */",
    "/* Generated by scripts/generate-theme-css.ts */",
    "",
  ];

  const themeNames = Object.keys(THEME_COLORS) as Array<keyof typeof THEME_COLORS>;

  for (const themeName of themeNames) {
    // Skip neutral - it's the default in :root
    if (themeName === "neutral") continue;

    const theme = THEME_COLORS[themeName];

    // Light mode
    lines.push(`.theme-${themeName} {`);
    for (const varName of THEME_SPECIFIC_VARS) {
      const value = theme.light[varName];
      if (value) {
        // Skip if it's same as base
        if (varName === "primary-foreground" && value === BASE_LIGHT["primary-foreground"]) {
          continue;
        }
        lines.push(`  --${varName}: ${value};`);
      }
    }
    lines.push("}");
    lines.push("");

    // Dark mode - need to handle both .dark.theme-X and .dark .theme-X
    lines.push(`.dark.theme-${themeName},`);
    lines.push(`.dark .theme-${themeName} {`);
    for (const varName of THEME_SPECIFIC_VARS) {
      const value = theme.dark[varName];
      if (value) {
        // Skip if it's same as base dark
        if (varName === "primary-foreground" && value === BASE_DARK["primary-foreground"]) {
          continue;
        }
        lines.push(`  --${varName}: ${value};`);
      }
    }
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

// Generate and write the file
const css = generateThemeCSS();
const outputPath = path.join(__dirname, "../src/styles/themes.css");

// Ensure directory exists
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, css);

console.log(`Generated theme CSS at ${outputPath}`);
console.log(`Total themes: ${Object.keys(THEME_COLORS).length - 1} (excluding neutral default)`);
