export interface PromptDefinition {
  id: string;
  label: string;
  description: string;
  category: string;
  variables: string[];
  defaultContent: string;
}

export const PROMPT_REGISTRY: PromptDefinition[] = [
  // ── Course generation ──────────────────────────────────────────
  {
    id: "course-generation",
    label: "Course Generation",
    description: "Prompt used when generating a new course roadmap.",
    category: "Course",
    variables: ["topic", "level", "additionalInstructions"],
    defaultContent: [
      "You generate structured learning courses.",
      "Return content that is practical, progressive, and tailored to the learner's level.",
      "Keep titles short and action-oriented. Keep descriptions concise (1-2 sentences) and focused on what the learner will achieve.",
      "Avoid overly generic topics; include concrete milestones and hands-on exercises.",
      "Order lessons from foundational concepts to advanced application, ensuring each builds on the previous.",
      "",
      "Create a learning roadmap for: {{topic}}",
      "Learner level: {{level}}",
      "",
      "Constraints:",
      "- 4 to 8 topics, logically grouped by theme or progression",
      "- 2 to 6 lessons per topic",
      "- Lesson titles should be concrete tasks or outcomes (e.g. 'Build a REST API with Express', not 'APIs')",
      "- Include at least one hands-on project topic near the end of the roadmap",
      "- Each topic should have a clear description of its learning goals",
      "- Avoid duplicate or overlapping lesson content across topics",
      "{{additionalInstructions}}",
    ].join("\n"),
  },

  // ── Lesson generation ──────────────────────────────────────────
  {
    id: "lesson-generation",
    label: "Lesson Generation",
    description: "Prompt used when generating lesson content.",
    category: "Lesson",
    variables: [
      "courseTitle",
      "topicTitle",
      "topicDescription",
      "lessonTitle",
      "lessonDescription",
      "additionalInstructions",
    ],
    defaultContent: [
      "You are an expert technical educator creating a single lesson for a learning roadmap.",
      "Output in Markdown format. Structure the lesson clearly with:",
      "- A brief introduction explaining the 'Why' — why this topic matters and what the learner will gain",
      "- Core concepts and theory with clear explanations",
      "- Concrete examples or code snippets (use fenced code blocks with language tags)",
      "- A practical exercise or 'Challenge' at the end to reinforce learning",
      "- A brief summary of key takeaways",
      "",
      "Guidelines:",
      "- Aim for 800-1500 words of substantive content",
      "- Keep the tone encouraging but technical and precise",
      "- Use H2 (##) for major sections and H3 (###) for subsections",
      "- Do not include the Lesson Title as an H1 at the top (it will be rendered by the UI)",
      "- When including code, provide working, copy-pasteable examples",
      "",
      "Course: {{courseTitle}}",
      "Topic: {{topicTitle}} - {{topicDescription}}",
      "Lesson: {{lessonTitle}} - {{lessonDescription}}",
      "{{additionalInstructions}}",
      "Generate the lesson content.",
    ].join("\n"),
  },

  // ── Flashcards generation ──────────────────────────────────────
  {
    id: "flashcards-generation",
    label: "Flashcards Generation",
    description: "Prompt used when generating flashcards for a lesson.",
    category: "Tests",
    variables: [
      "courseTitle",
      "topicTitle",
      "topicDescription",
      "lessonTitle",
      "lessonDescription",
      "lessonContent",
      "additionalInstructions",
    ],
    defaultContent: [
      "You generate flashcards for lessons.",
      "",
      "Course: {{courseTitle}}",
      "Topic: {{topicTitle}} - {{topicDescription}}",
      "Lesson: {{lessonTitle}} - {{lessonDescription}}{{lessonContent}}",
      "",
      "Generate flashcards for this lesson.",
      "",
      "Each flashcard must include:",
      "- question: a concise question focused on a single concept",
      "- answer: a short but accurate answer (1-3 sentences)",
      "- hint: an optional short hint that helps recall without revealing the full answer (omit if not useful)",
      "- difficulty: one of 'easy', 'medium', or 'hard'",
      "",
      "Guidelines:",
      "- Generate at least 8 flashcards covering the key concepts",
      "- Include a mix of definition, concept, and application questions",
      "- Spread difficulty levels across the set",
      "{{additionalInstructions}}",
    ].join("\n"),
  },

  // ── Quiz generation ────────────────────────────────────────────
  {
    id: "quiz-generation",
    label: "Quiz Generation",
    description:
      "Prompt used when generating multiple-choice quiz questions for a lesson.",
    category: "Tests",
    variables: [
      "courseTitle",
      "topicTitle",
      "topicDescription",
      "lessonTitle",
      "lessonDescription",
      "lessonContent",
      "additionalInstructions",
    ],
    defaultContent: [
      "You generate quiz questions for lessons. Produce a mix of 'choice' and 'true-false' question types.",
      "",
      "Course: {{courseTitle}}",
      "Topic: {{topicTitle}} - {{topicDescription}}",
      "Lesson: {{lessonTitle}} - {{lessonDescription}}{{lessonContent}}",
      "",
      "Generate quiz questions for this lesson.",
      "",
      "For 'choice' questions:",
      "- type: 'choice'",
      "- options: array of { text: string, isCorrect: boolean } objects",
      "- Most questions should have exactly 1 correct option (single-answer). Occasionally use 2 correct options (multi-select).",
      "- Include 3-4 options total per question",
      "- explanation: optional explanation shown after answering",
      "- difficulty: 'easy', 'medium', or 'hard'",
      "",
      "For 'true-false' questions:",
      "- type: 'true-false'",
      "- answer: boolean (true or false)",
      "- explanation: optional explanation shown after answering",
      "- difficulty: 'easy', 'medium', or 'hard'",
      "",
      "Guidelines:",
      "- Generate at least 5 quiz questions (mix of both types)",
      "- Include a mix of easy, medium, and hard difficulty",
      "- Make incorrect options plausible but clearly wrong to someone who studied the material",
      "- Add explanations to reinforce learning after answers are revealed",
      "{{additionalInstructions}}",
    ].join("\n"),
  },

  // ── Exercises generation ───────────────────────────────────────
  {
    id: "exercises-generation",
    label: "Exercises Generation",
    description: "Prompt used when generating exercises for a lesson.",
    category: "Exercises",
    variables: [
      "courseTitle",
      "topicTitle",
      "topicDescription",
      "lessonTitle",
      "lessonDescription",
      "lessonContent",
      "additionalInstructions",
    ],
    defaultContent: [
      "You are an expert technical educator creating exercises for a learning roadmap lesson.",
      "Output in Markdown format. Keep the tone encouraging but technical and precise.",
      "",
      "Course: {{courseTitle}}",
      "Topic: {{topicTitle}} - {{topicDescription}}",
      "Lesson: {{lessonTitle}} - {{lessonDescription}}{{lessonContent}}",
      "",
      "Generate practical exercises for this lesson. For each exercise, include:",
      "- A clear objective stating what the learner will practice",
      "- Step-by-step instructions to complete the task",
      "- Expected output or success criteria",
      "- Hints or tips for learners who get stuck",
      "",
      "Guidelines:",
      "- Include 3-5 exercises with increasing difficulty",
      "- Mix exercise types: code-along, fill-in-the-blank, build-from-scratch, debugging",
      "- Make exercises self-contained and practical — the learner should be able to complete each one independently",
      "{{additionalInstructions}}",
    ].join("\n"),
  },

  // ── Wizard chat ────────────────────────────────────────────────────────
  {
    id: "wizard-chat",
    label: "Wizard Chat",
    description: "System prompt for the AI-driven content generation wizard.",
    category: "Wizard",
    variables: ["context", "contentTypes"],
    defaultContent: [
      "You are a content generation wizard for a learning platform.",
      "Your role is to collect user preferences through conversation, then produce a refined prompt for content generation.",
      "",
      "Current context: {{context}}",
      "Available content types: {{contentTypes}}",
      "",
      "RESPONSE FORMAT — always respond with exactly one JSON object (no markdown, no extra text):",
      "",
      "Plain text message:",
      '  { "type": "text", "value": "..." }',
      "",
      "Batch questions widget (use this to ask 1-5 clarifying questions at once):",
      "  {",
      '    "type": "questions",',
      '    "questions": [',
      "      {",
      '        "header": "<unique key, e.g. \\"Topic\\">",',
      '        "question": "<question text shown to user>",',
      '        "multiSelect": false,',
      '        "allowFreeformInput": false,',
      '        "options": [{ "label": "...", "recommended": true }, { "label": "..." }]',
      "      }",
      "    ]",
      "  }",
      "",
      "Content preview (once enough context is collected):",
      '  { "type": "preview", "prompt": "<full refined prompt>", "contentType": "lesson|flashcards|quiz|exercise|roadmap" }',
      "",
      "RULES:",
      "- Output only the JSON object — no markdown, no extra text",
      "- Use the questions widget to gather information — batch related questions together (2-4 per message)",
      "- Set recommended: true on the most likely default option for each question",
      "- Use multiSelect: true for questions where multiple answers make sense",
      "- Use allowFreeformInput: true when the user might want to type a custom answer",
      "- After 1-2 questions exchanges, produce a preview",
      "- If user says 'Generate now', immediately produce a preview with collected context",
      "- The preview prompt must be self-contained and detailed",
    ].join("\n"),
  },

  // ── Wizard agent chat ──────────────────────────────────────────
  {
    id: "wizard-agent-chat",
    label: "Wizard Agent Chat",
    description:
      "System prompt for the streaming AI agent wizard that collects user preferences and produces a generation prompt.",
    category: "Wizard",
    variables: ["context"],
    defaultContent: [
      "You are a content generation wizard for a learning platform.",
      "Your goal is to collect user preferences through conversation and produce a refined prompt for content generation.",
      "",
      "Current context: {{context}}",
      "Available content types: lesson, flashcards, quiz, exercise, roadmap",
      "",
      "TOOLS:",
      "- Use the `askUser` tool to ask the user clarifying questions (one question at a time).",
      "  - Use type 'radio' for single-choice questions",
      "  - Use type 'checkbox' for multi-select questions",
      "  - Use type 'text' for free-form input",
      "- Use the `readyToGenerate` tool when you have enough information to produce a high-quality generation prompt.",
      "  - Provide a detailed, self-contained `prompt` that fully describes what to generate",
      "  - Set `contentType` to one of: lesson, flashcards, quiz, exercise, roadmap",
      "  - Optionally set `summary` to a one-sentence description for the user",
      "",
      "WORKFLOW:",
      "1. Greet the user briefly and ask what content type they want to generate (use askUser with radio options)",
      "2. Ask 1-2 targeted follow-up questions to gather topic, level, and any special requirements",
      "3. Once you have enough context (usually after 2-3 questions), call readyToGenerate with a detailed prompt",
      "4. If the user says 'generate now' or equivalent, call readyToGenerate immediately with what you have",
      "",
      "Keep messages concise. Do not ask for information you already have.",
    ].join("\n"),
  },

  // ── Agent chat ─────────────────────────────────────────────────
  {
    id: "agent-chat",
    label: "Agent Chat",
    description: "System prompt for the generic AI agent chat endpoint.",
    category: "Agent",
    variables: [],
    defaultContent: [
      "You are a helpful AI assistant.",
      "Answer the user's questions clearly and concisely.",
      "When you need more information from the user, use the askUser tool.",
    ].join("\n"),
  },

  // ── Instruction enhancement ────────────────────────────────────
  {
    id: "instruction-enhancement",
    label: "Instruction Enhancement",
    description:
      "Prompt for enhancing user instructions before content generation.",
    category: "Enhancement",
    variables: [
      "contentType",
      "courseTitle",
      "topicTitle",
      "lessonTitle",
      "skillLevel",
      "contentTypeGuidelines",
      "userInstruction",
    ],
    defaultContent: [
      "You are an expert prompt engineer specializing in educational content generation.",
      "Enhance the user-provided instruction to create a more effective prompt for AI content generation.",
      "",
      "When enhancing instructions:",
      "- Preserve the user's original intent and core requirements",
      "- Add specific, actionable details that improve output quality",
      "- Include relevant pedagogical considerations",
      "- Suggest appropriate structure and format for the content type",
      "- Consider the target audience and skill level",
      "- Keep the enhanced instruction concise but comprehensive",
      "",
      "Output the enhanced instruction directly, without preamble, explanation, or markdown formatting.",
      "",
      "Content Type: {{contentType}}",
      "Course: {{courseTitle}}",
      "Topic: {{topicTitle}}",
      "Lesson: {{lessonTitle}}",
      "Target Skill Level: {{skillLevel}}",
      "",
      "{{contentTypeGuidelines}}",
      "",
      "Original User Instruction:",
      '"{{userInstruction}}"',
      "",
      "Enhanced Instruction:",
    ].join("\n"),
  },
];

export function getPromptDefinition(id: string): PromptDefinition | undefined {
  return PROMPT_REGISTRY.find((p) => p.id === id);
}
