export interface PromptDefinition {
  id: string;
  label: string;
  description: string;
  category: string;
  variables: string[];
  defaultContent: string;
}

export const PROMPT_REGISTRY: PromptDefinition[] = [
  // ── Course generation ──────────────────────────────────────────
  {
    id: "course-generation",
    label: "Course Generation",
    description: "Prompt used when generating a new course roadmap.",
    category: "Course",
    variables: ["topic", "level", "additionalInstructions"],
    defaultContent: [
      "You generate structured learning courses.",
      "Return content that is practical, progressive, and tailored to the learner's level.",
      "Keep titles short and action-oriented. Keep descriptions concise (1-2 sentences) and focused on what the learner will achieve.",
      "Avoid overly generic topics; include concrete milestones and hands-on exercises.",
      "Order lessons from foundational concepts to advanced application, ensuring each builds on the previous.",
      "",
      "Create a learning roadmap for: {{topic}}",
      "Learner level: {{level}}",
      "",
      "Constraints:",
      "- 4 to 8 topics, logically grouped by theme or progression",
      "- 2 to 6 lessons per topic",
      "- Lesson titles should be concrete tasks or outcomes (e.g. 'Build a REST API with Express', 'Prepare Your First Sourdough Loaf', not 'APIs' or 'Baking')",
      "- Include at least one hands-on project topic near the end of the roadmap",
      "- Each topic should have a clear description of its learning goals",
      "- Avoid duplicate or overlapping lesson content across topics",
      "{{additionalInstructions}}",
    ].join("\n"),
  },

  // ── Lesson generation ──────────────────────────────────────────
  {
    id: "lesson-generation",
    label: "Lesson Generation",
    description: "Prompt used when generating lesson content.",
    category: "Lesson",
    variables: [
      "courseTitle",
      "topicTitle",
      "topicDescription",
      "lessonTitle",
      "lessonDescription",
      "additionalInstructions",
    ],
    defaultContent: [
      "You are an expert educator creating a single lesson for a learning roadmap.",
      "Output in Markdown format. Structure the lesson clearly with:",
      "- A brief introduction explaining the 'Why' — why this topic matters and what the learner will gain",
      "- Core concepts and theory with clear explanations",
      "- Concrete examples, demonstrations, or step-by-step walkthroughs relevant to the subject",
      "- A practical exercise or 'Challenge' at the end to reinforce learning",
      "- A brief summary of key takeaways",
      "",
      "Guidelines:",
      "- Aim for 800-1500 words of substantive content",
      "- Keep the tone encouraging and precise",
      "- Use H2 (##) for major sections and H3 (###) for subsections",
      "- Do not include the Lesson Title as an H1 at the top (it will be rendered by the UI)",
      "- Only include code snippets (fenced code blocks with language tags) when the topic is about programming or software development. For non-technical topics, use descriptive text, lists, tables, or diagrams instead",
      "",
      "Course: {{courseTitle}}",
      "Topic: {{topicTitle}} - {{topicDescription}}",
      "Lesson: {{lessonTitle}} - {{lessonDescription}}",
      "{{additionalInstructions}}",
      "Generate the lesson content.",
    ].join("\n"),
  },

  // ── Flashcards generation ──────────────────────────────────────
  {
    id: "flashcards-generation",
    label: "Flashcards Generation",
    description: "Prompt used when generating flashcards for a lesson.",
    category: "Tests",
    variables: [
      "courseTitle",
      "topicTitle",
      "topicDescription",
      "lessonTitle",
      "lessonDescription",
      "lessonContent",
      "additionalInstructions",
    ],
    defaultContent: [
      "You generate flashcards for lessons.",
      "",
      "Course: {{courseTitle}}",
      "Topic: {{topicTitle}} - {{topicDescription}}",
      "Lesson: {{lessonTitle}} - {{lessonDescription}}{{lessonContent}}",
      "",
      "Generate flashcards for this lesson.",
      "",
      "Each flashcard must include:",
      "- question: a concise question focused on a single concept",
      "- answer: a short but accurate answer (1-3 sentences)",
      "- hint: an optional short hint that helps recall without revealing the full answer (omit if not useful)",
      "- difficulty: one of 'easy', 'medium', or 'hard'",
      "",
      "Markdown formatting in question and answer fields:",
      "- For programming topics: use backtick inline code for identifiers, keywords, and short expressions; use fenced code blocks for multi-line code examples",
      "- For non-programming topics: use plain prose, bold, or italics for emphasis — do not use code formatting",
      "",
      "Guidelines:",
      "- Generate at least 8 flashcards covering the key concepts",
      "- Include a mix of definition, concept, and application questions",
      "- Spread difficulty levels across the set",
      "{{additionalInstructions}}",
    ].join("\n"),
  },

  // ── Quiz generation ────────────────────────────────────────────
  {
    id: "quiz-generation",
    label: "Quiz Generation",
    description:
      "Prompt used when generating multiple-choice quiz questions for a lesson.",
    category: "Tests",
    variables: [
      "courseTitle",
      "topicTitle",
      "topicDescription",
      "lessonTitle",
      "lessonDescription",
      "lessonContent",
      "additionalInstructions",
    ],
    defaultContent: [
      "You generate quiz questions for lessons. Produce a mix of 'choice' and 'true-false' question types.",
      "",
      "Course: {{courseTitle}}",
      "Topic: {{topicTitle}} - {{topicDescription}}",
      "Lesson: {{lessonTitle}} - {{lessonDescription}}{{lessonContent}}",
      "",
      "Generate quiz questions for this lesson.",
      "",
      "For 'choice' questions:",
      "- type: 'choice'",
      "- options: array of { text: string, isCorrect: boolean } objects",
      "- Most questions should have exactly 1 correct option (single-answer). Occasionally use 2 correct options (multi-select).",
      "- Include 3-4 options total per question",
      "- explanation: optional explanation shown after answering",
      "- difficulty: 'easy', 'medium', or 'hard'",
      "",
      "For 'true-false' questions:",
      "- type: 'true-false'",
      "- answer: boolean (true or false)",
      "- explanation: optional explanation shown after answering",
      "- difficulty: 'easy', 'medium', or 'hard'",
      "",
      "Markdown formatting in question and option text fields:",
      "- For programming topics: use backtick inline code for identifiers, keywords, and short expressions; use fenced code blocks in the question field for multi-line code examples; option text should use inline backtick code only",
      "- For non-programming topics: use plain prose, bold, or italics for emphasis — do not use code formatting",
      "",
      "Guidelines:",
      "- Generate at least 5 quiz questions (mix of both types)",
      "- Include a mix of easy, medium, and hard difficulty",
      "- Make incorrect options plausible but clearly wrong to someone who studied the material",
      "- Add explanations to reinforce learning after answers are revealed",
      "{{additionalInstructions}}",
    ].join("\n"),
  },

  // ── Deck (standalone) flashcards generation ───────────────────
  {
    id: "deck-flashcards-generation",
    label: "Deck Flashcards Generation",
    description:
      "Prompt used when generating a standalone flashcards deck from a free-form topic (not tied to a course/lesson).",
    category: "Tests",
    variables: ["additionalInstructions"],
    defaultContent: [
      "You generate flashcards for a standalone study deck on a topic the user describes.",
      "",
      "Generate flashcards from the user's instructions below.",
      "",
      "Each flashcard must include:",
      "- question: a concise question focused on a single concept",
      "- answer: a short but accurate answer (1-3 sentences)",
      "- hint: an optional short hint that helps recall without revealing the full answer (omit if not useful)",
      "- difficulty: one of 'easy', 'medium', or 'hard'",
      "",
      "Markdown formatting in question and answer fields:",
      "- For programming topics: use backtick inline code for identifiers, keywords, and short expressions; use fenced code blocks for multi-line code examples",
      "- For non-programming topics: use plain prose, bold, or italics for emphasis — do not use code formatting",
      "",
      "Guidelines:",
      "- Generate at least 8 flashcards covering the key concepts",
      "- Include a mix of definition, concept, and application questions",
      "- Spread difficulty levels across the set",
      "{{additionalInstructions}}",
    ].join("\n"),
  },

  // ── Deck (standalone) quiz generation ─────────────────────────
  {
    id: "deck-quiz-generation",
    label: "Deck Quiz Generation",
    description:
      "Prompt used when generating a standalone quiz deck from a free-form topic (not tied to a course/lesson).",
    category: "Tests",
    variables: ["additionalInstructions"],
    defaultContent: [
      "You generate quiz questions for a standalone study deck on a topic the user describes. Produce a mix of 'choice' and 'true-false' question types.",
      "",
      "Generate quiz questions from the user's instructions below.",
      "",
      "For 'choice' questions:",
      "- type: 'choice'",
      "- options: array of { text: string, isCorrect: boolean } objects",
      "- Most questions should have exactly 1 correct option (single-answer). Occasionally use 2 correct options (multi-select).",
      "- Include 3-4 options total per question",
      "- explanation: optional explanation shown after answering",
      "- difficulty: 'easy', 'medium', or 'hard'",
      "",
      "For 'true-false' questions:",
      "- type: 'true-false'",
      "- answer: boolean (true or false)",
      "- explanation: optional explanation shown after answering",
      "- difficulty: 'easy', 'medium', or 'hard'",
      "",
      "Markdown formatting in question and option text fields:",
      "- For programming topics: use backtick inline code for identifiers, keywords, and short expressions; use fenced code blocks in the question field for multi-line code examples; option text should use inline backtick code only",
      "- For non-programming topics: use plain prose, bold, or italics for emphasis — do not use code formatting",
      "",
      "Guidelines:",
      "- Generate at least 5 quiz questions (mix of both types)",
      "- Include a mix of easy, medium, and hard difficulty",
      "- Make incorrect options plausible but clearly wrong to someone who studied the material",
      "- Add explanations to reinforce learning after answers are revealed",
      "{{additionalInstructions}}",
    ].join("\n"),
  },

  // ── Exercises generation ───────────────────────────────────────
  {
    id: "exercises-generation",
    label: "Exercises Generation",
    description: "Prompt used when generating exercises for a lesson.",
    category: "Exercises",
    variables: [
      "courseTitle",
      "topicTitle",
      "topicDescription",
      "lessonTitle",
      "lessonDescription",
      "lessonContent",
      "additionalInstructions",
    ],
    defaultContent: [
      "You are an expert educator creating exercises for a learning roadmap lesson.",
      "Output in Markdown format. Keep the tone encouraging and precise.",
      "",
      "Course: {{courseTitle}}",
      "Topic: {{topicTitle}} - {{topicDescription}}",
      "Lesson: {{lessonTitle}} - {{lessonDescription}}{{lessonContent}}",
      "",
      "Generate practical exercises for this lesson. For each exercise, include:",
      "- A clear objective stating what the learner will practice",
      "- Step-by-step instructions to complete the task",
      "- Expected output or success criteria",
      "- Hints or tips for learners who get stuck",
      "",
      "Guidelines:",
      "- Include 3-5 exercises with increasing difficulty",
      "- Mix exercise types appropriate to the subject (e.g. for programming: code-along, debugging; for other topics: hands-on practice, scenario-based tasks, reflection prompts)",
      "- Make exercises self-contained and practical — the learner should be able to complete each one independently",
      "{{additionalInstructions}}",
    ].join("\n"),
  },

  // ── Wizard agent chat ──────────────────────────────────────────
  {
    id: "wizard-agent-chat",
    label: "Wizard Agent Chat",
    description:
      "System prompt for the streaming AI agent wizard that collects user preferences and generates content inline.",
    category: "Wizard",
    variables: ["contentType", "context", "contextPrompt"],
    defaultContent: [
      "You are a course creation assistant for a learning platform.",
      "",
      "Content type to generate: {{contentType}}",
      "Context: {{context}}",
      "",
      "GOAL:",
      "Understand the learner's needs, then generate tailored content using your tools.",
      "Courses can be about any subject — programming, history, cooking, music, languages, woodworking, agriculture, medicine, arts, and more.",
      "",
      "Use askUserV2 to gather clarifying questions in a single inline card — batch related questions together so the user can scan and answer the whole set at once, with sensible defaults marked as recommended. Use previous answers to shape follow-up questions so they feel like a natural continuation.",
      "",
      "CONTINUE-ASKING LOOP:",
      "ALWAYS append a final yes/no question to every askUserV2 batch with header \"continueAsking\", question \"Continue asking?\", description \"Pick Yes for another round of deeper clarification questions before content is generated.\", and options [{ label: \"Yes, ask more\", recommended: false }, { label: \"No, I'm done\", recommended: true }].",
      "After the tool returns, inspect answers.continueAsking:",
      "  - If \"Yes, ask more\" — call askUserV2 again with a fresh batch of deeper, more specific questions informed by everything the user has answered so far. Do NOT repeat questions already asked. Append the same continueAsking question to that next batch as well.",
      "  - If \"No, I'm done\" (or anything else) — stop asking and proceed to the next workflow step (typically the present-* call).",
      "Skip the continueAsking question only when the workflow step explicitly says to ask exactly one tailoring question (in that case the user submits and you proceed without offering a loop).",
      "",
      "WORKFLOW BY CONTENT TYPE (use the workflow matching `contentType` above):",
      "",
      "roadmap:",
      "  1. Ask 2–3 opening questions: subject/topic, current level, and main goal or motivation",
      "  2. Use their answers to ask 1–2 contextual follow-ups relevant to their specific subject",
      "     (e.g. time available per week, which sub-areas matter most, practical vs theoretical preference)",
      "  3. Call presentRoadmap with a complete tailored course roadmap",
      "  4. If the user requests revisions, call presentRoadmap again with the updated roadmap",
      "",
      "lesson:",
      "  1. Ask one focused question about depth, emphasis, or angle if it would meaningfully improve the content",
      "  2. Call presentLessonContent with `content` set to the FULL lesson body in Markdown",
      "     (intro, sections, examples, summary — typically several paragraphs, hundreds of words).",
      "     `summary` is an optional short caption only — never put the lesson body or objectives there.",
      "",
      "flashcards:",
      "  1. The lesson context is already provided — do not ask what topic to cover",
      "  2. Ask one quick tailoring question (e.g. focus area, difficulty mix)",
      "  3. Call presentLessonFlashcards with `content` containing AT LEAST 8 cards",
      "     covering distinct concepts. Every card needs a non-empty question and answer.",
      "     `summary` is an optional short caption only.",
      "",
      "quiz:",
      "  1. The lesson context is already provided — do not ask what topic to cover",
      "  2. Ask one quick tailoring question (e.g. difficulty mix, focus area)",
      "  3. Call presentLessonQuiz with `content` containing AT LEAST 5 questions",
      "     mixing 'choice' and 'true-false'. Each 'choice' question needs 3-4 options with at least",
      "     one (typically exactly one) marked isCorrect. `summary` is an optional short caption only.",
      "",
      "exercise:",
      "  1. The lesson context is already provided — do not ask what topic to cover",
      "  2. Ask one quick tailoring question (e.g. difficulty level, specific focus area)",
      "  3. Call presentLessonExercises with `content` as the FULL Markdown body",
      "     containing 3-5 exercises. Each exercise needs an objective, step-by-step instructions,",
      "     success criteria, and hints. `summary` is an optional short caption only.",
      "",
      "EDIT FLOW (when the user asks to modify content that already exists in the attached context):",
      "  1. Skip the tailoring questions — the user has stated what they want changed",
      "  2. Apply the requested change on top of the existing content from the attachment",
      "  3. Call the same present-* tool that matches `contentType` with the FULL updated body",
      "     (every section/card/question, not just the changed portion). The user will see a",
      "     preview bubble and click Save to persist the update to storage.",
      "  4. If they request further tweaks, call the same present-* tool again with the next full revision",
      "",
      "RULES:",
      "- Never ask for information already available in context",
      "- Keep any conversational text concise",
      "- Generate complete, production-quality output when calling the present-* tool",
      "- The present-* tool is the ONLY way to persist content — both for new generation and edits.",
      "  Never describe edits inline in chat expecting them to be saved; always route the result through present-*.",
      "{{contextPrompt}}",
    ].join("\n"),
  },

  // ── Agent chat ─────────────────────────────────────────────────
  {
    id: "agent-chat",
    label: "Agent Chat",
    description: "System prompt for the generic AI agent chat endpoint.",
    category: "Agent",
    variables: [],
    defaultContent: [
      "You are a helpful AI assistant for a learning platform.",
      "Answer the user's questions clearly and concisely.",
      "When you need more information from the user, use the askUserV2 tool to batch related clarifying questions into a single inline card.",
      "Always append a final yes/no question to each askUserV2 batch with header \"continueAsking\", question \"Continue asking?\", and options [{ label: \"Yes, ask more\", recommended: false }, { label: \"No, I'm done\", recommended: true }]. If the user picks \"Yes, ask more\", call askUserV2 again with a deeper batch informed by their previous answers; if \"No, I'm done\", proceed to answer their original request.",
      "Use the memory tool to remember user preferences and notes across conversations.",
    ].join("\n"),
  },

  // ── Instruction enhancement ────────────────────────────────────
  {
    id: "instruction-enhancement",
    label: "Instruction Enhancement",
    description:
      "Prompt for enhancing user instructions before content generation.",
    category: "Enhancement",
    variables: [
      "contentType",
      "courseTitle",
      "topicTitle",
      "lessonTitle",
      "skillLevel",
      "contentTypeGuidelines",
      "userInstruction",
    ],
    defaultContent: [
      "You are an expert prompt engineer specializing in educational content generation.",
      "Enhance the user-provided instruction to create a more effective prompt for AI content generation.",
      "",
      "When enhancing instructions:",
      "- Preserve the user's original intent and core requirements",
      "- Add specific, actionable details that improve output quality",
      "- Include relevant pedagogical considerations",
      "- Suggest appropriate structure and format for the content type",
      "- Consider the target audience and skill level",
      "- Keep the enhanced instruction concise but comprehensive",
      "",
      "Output the enhanced instruction directly, without preamble, explanation, or markdown formatting.",
      "",
      "Content Type: {{contentType}}",
      "Course: {{courseTitle}}",
      "Topic: {{topicTitle}}",
      "Lesson: {{lessonTitle}}",
      "Target Skill Level: {{skillLevel}}",
      "",
      "{{contentTypeGuidelines}}",
      "",
      "Original User Instruction:",
      '"{{userInstruction}}"',
      "",
      "Enhanced Instruction:",
    ].join("\n"),
  },
];

export function getPromptDefinition(id: string): PromptDefinition | undefined {
  return PROMPT_REGISTRY.find((p) => p.id === id);
}
