/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseCourseIdRouteImport } from './routes/course.$courseId'
import { Route as CourseCourseIdIndexRouteImport } from './routes/course.$courseId.index'
import { Route as CourseCourseIdLessonLessonIdRouteImport } from './routes/course.$courseId.lesson.$lessonId'
import { Route as CourseCourseIdLessonLessonIdIndexRouteImport } from './routes/course.$courseId.lesson.$lessonId.index'
import { Route as CourseCourseIdLessonLessonIdTestsRouteImport } from './routes/course.$courseId.lesson.$lessonId.tests'
import { Route as CourseCourseIdLessonLessonIdExercisesRouteImport } from './routes/course.$courseId.lesson.$lessonId.exercises'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdIndexRoute = CourseCourseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CourseCourseIdRoute,
} as any)
const CourseCourseIdLessonLessonIdRoute =
  CourseCourseIdLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => CourseCourseIdRoute,
  } as any)
const CourseCourseIdLessonLessonIdIndexRoute =
  CourseCourseIdLessonLessonIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CourseCourseIdLessonLessonIdRoute,
  } as any)
const CourseCourseIdLessonLessonIdTestsRoute =
  CourseCourseIdLessonLessonIdTestsRouteImport.update({
    id: '/tests',
    path: '/tests',
    getParentRoute: () => CourseCourseIdLessonLessonIdRoute,
  } as any)
const CourseCourseIdLessonLessonIdExercisesRoute =
  CourseCourseIdLessonLessonIdExercisesRouteImport.update({
    id: '/exercises',
    path: '/exercises',
    getParentRoute: () => CourseCourseIdLessonLessonIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/course/$courseId': typeof CourseCourseIdRouteWithChildren
  '/course/$courseId/': typeof CourseCourseIdIndexRoute
  '/course/$courseId/lesson/$lessonId': typeof CourseCourseIdLessonLessonIdRouteWithChildren
  '/course/$courseId/lesson/$lessonId/exercises': typeof CourseCourseIdLessonLessonIdExercisesRoute
  '/course/$courseId/lesson/$lessonId/tests': typeof CourseCourseIdLessonLessonIdTestsRoute
  '/course/$courseId/lesson/$lessonId/': typeof CourseCourseIdLessonLessonIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/course/$courseId': typeof CourseCourseIdIndexRoute
  '/course/$courseId/lesson/$lessonId/exercises': typeof CourseCourseIdLessonLessonIdExercisesRoute
  '/course/$courseId/lesson/$lessonId/tests': typeof CourseCourseIdLessonLessonIdTestsRoute
  '/course/$courseId/lesson/$lessonId': typeof CourseCourseIdLessonLessonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/course/$courseId': typeof CourseCourseIdRouteWithChildren
  '/course/$courseId/': typeof CourseCourseIdIndexRoute
  '/course/$courseId/lesson/$lessonId': typeof CourseCourseIdLessonLessonIdRouteWithChildren
  '/course/$courseId/lesson/$lessonId/exercises': typeof CourseCourseIdLessonLessonIdExercisesRoute
  '/course/$courseId/lesson/$lessonId/tests': typeof CourseCourseIdLessonLessonIdTestsRoute
  '/course/$courseId/lesson/$lessonId/': typeof CourseCourseIdLessonLessonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/course/$courseId'
    | '/course/$courseId/'
    | '/course/$courseId/lesson/$lessonId'
    | '/course/$courseId/lesson/$lessonId/exercises'
    | '/course/$courseId/lesson/$lessonId/tests'
    | '/course/$courseId/lesson/$lessonId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/course/$courseId'
    | '/course/$courseId/lesson/$lessonId/exercises'
    | '/course/$courseId/lesson/$lessonId/tests'
    | '/course/$courseId/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/course/$courseId'
    | '/course/$courseId/'
    | '/course/$courseId/lesson/$lessonId'
    | '/course/$courseId/lesson/$lessonId/exercises'
    | '/course/$courseId/lesson/$lessonId/tests'
    | '/course/$courseId/lesson/$lessonId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  CourseCourseIdRoute: typeof CourseCourseIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId/': {
      id: '/course/$courseId/'
      path: '/'
      fullPath: '/course/$courseId/'
      preLoaderRoute: typeof CourseCourseIdIndexRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/lesson/$lessonId': {
      id: '/course/$courseId/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/course/$courseId/lesson/$lessonId'
      preLoaderRoute: typeof CourseCourseIdLessonLessonIdRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/lesson/$lessonId/': {
      id: '/course/$courseId/lesson/$lessonId/'
      path: '/'
      fullPath: '/course/$courseId/lesson/$lessonId/'
      preLoaderRoute: typeof CourseCourseIdLessonLessonIdIndexRouteImport
      parentRoute: typeof CourseCourseIdLessonLessonIdRoute
    }
    '/course/$courseId/lesson/$lessonId/tests': {
      id: '/course/$courseId/lesson/$lessonId/tests'
      path: '/tests'
      fullPath: '/course/$courseId/lesson/$lessonId/tests'
      preLoaderRoute: typeof CourseCourseIdLessonLessonIdTestsRouteImport
      parentRoute: typeof CourseCourseIdLessonLessonIdRoute
    }
    '/course/$courseId/lesson/$lessonId/exercises': {
      id: '/course/$courseId/lesson/$lessonId/exercises'
      path: '/exercises'
      fullPath: '/course/$courseId/lesson/$lessonId/exercises'
      preLoaderRoute: typeof CourseCourseIdLessonLessonIdExercisesRouteImport
      parentRoute: typeof CourseCourseIdLessonLessonIdRoute
    }
  }
}

interface CourseCourseIdLessonLessonIdRouteChildren {
  CourseCourseIdLessonLessonIdExercisesRoute: typeof CourseCourseIdLessonLessonIdExercisesRoute
  CourseCourseIdLessonLessonIdTestsRoute: typeof CourseCourseIdLessonLessonIdTestsRoute
  CourseCourseIdLessonLessonIdIndexRoute: typeof CourseCourseIdLessonLessonIdIndexRoute
}

const CourseCourseIdLessonLessonIdRouteChildren: CourseCourseIdLessonLessonIdRouteChildren =
  {
    CourseCourseIdLessonLessonIdExercisesRoute:
      CourseCourseIdLessonLessonIdExercisesRoute,
    CourseCourseIdLessonLessonIdTestsRoute:
      CourseCourseIdLessonLessonIdTestsRoute,
    CourseCourseIdLessonLessonIdIndexRoute:
      CourseCourseIdLessonLessonIdIndexRoute,
  }

const CourseCourseIdLessonLessonIdRouteWithChildren =
  CourseCourseIdLessonLessonIdRoute._addFileChildren(
    CourseCourseIdLessonLessonIdRouteChildren,
  )

interface CourseCourseIdRouteChildren {
  CourseCourseIdIndexRoute: typeof CourseCourseIdIndexRoute
  CourseCourseIdLessonLessonIdRoute: typeof CourseCourseIdLessonLessonIdRouteWithChildren
}

const CourseCourseIdRouteChildren: CourseCourseIdRouteChildren = {
  CourseCourseIdIndexRoute: CourseCourseIdIndexRoute,
  CourseCourseIdLessonLessonIdRoute:
    CourseCourseIdLessonLessonIdRouteWithChildren,
}

const CourseCourseIdRouteWithChildren = CourseCourseIdRoute._addFileChildren(
  CourseCourseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  CourseCourseIdRoute: CourseCourseIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
